/* Curated study content. Source worksheet text and figures are preserved separately. */
const OPENSTAX='https://openstax.org/books/anatomy-and-physiology-2e/pages/';
const UNITS=[
{id:'foundations',title:'The language of anatomy',subtitle:'Body directions, planes & homeostasis',icon:'compass',color:'#eee8f6',tone:'#8a6ea8',source:'src5',ref:'1-6-anatomical-terminology',cards:[
['Anatomical position','Anatomical descriptions use a standard reference: standing upright, facing forward, arms at the sides, palms facing forward, and feet directed forward. Right and left always refer to the person being described.','Use the subject’s right and left, not the viewer’s.','In anatomical position, which direction do the palms face?',['Anteriorly','Posteriorly','Medially','Inferiorly'],0],
['Directional pairs','Superior means toward the head; inferior means toward the feet. Anterior is toward the front and posterior toward the back. Medial is toward the midline, while lateral is away from it.','The sternum is anterior to the heart; the heart is medial to the lungs.','The sternum is _____ to the heart.',['Posterior','Anterior','Inferior','Lateral'],1],
['Proximal and distal','Proximal describes a structure closer to a limb’s attachment to the trunk. Distal describes a structure farther from that attachment. These are relative relationships, not fixed locations.','The elbow is proximal to the wrist and distal to the shoulder.','The wrist is _____ to the elbow.',['Proximal','Superior','Distal','Medial'],2],
['Planes of the body','A sagittal plane divides right and left portions; a midsagittal plane divides equal right and left halves. A frontal (coronal) plane divides anterior and posterior portions. A transverse plane divides superior and inferior portions.','Sagittal: right/left. Frontal: front/back. Transverse: top/bottom.','Which plane divides the body into superior and inferior portions?',['Frontal','Sagittal','Midsagittal','Transverse'],3],
['Keeping a stable internal environment','Homeostasis maintains internal conditions within a functional range. A receptor detects change, a control center evaluates it, and an effector produces a response. Negative feedback opposes the initial change.','Negative feedback reduces a disturbance; it does not mean a harmful response.','Sweating in response to rising body temperature illustrates what?',['Positive feedback','Negative feedback','Anatomical variation','Passive immunity'],1]
]},
{id:'chemistry',title:'Chemistry of life',subtitle:'Molecules, proteins & chemical reactions',icon:'atom',color:'#f7eee1',tone:'#b88c4e',source:'src15',ref:'2-5-organic-compounds-essential-to-human-functioning',cards:[
['Atoms, molecules and compounds','Atoms are units of chemical elements. A molecule contains two or more atoms bonded together. A compound contains at least two different elements: O₂ is a molecule but not a compound; H₂O is both.','A molecule does not necessarily contain different elements.','Which is a molecule but not a compound?',['H₂O','CO₂','O₂','NaCl'],2],
['Building and breaking molecules','Dehydration synthesis joins smaller molecules while releasing water. Hydrolysis uses water to split a bond. These reactions help assemble and digest many biological polymers.','Dehydration builds; hydrolysis breaks.','Which process uses water to split a chemical bond?',['Dehydration synthesis','Hydrolysis','Denaturation','Diffusion'],1],
['Proteins and their shape','Amino acids are linked by peptide bonds to form polypeptides. The amino-acid sequence helps determine folding and function. Denaturation disrupts higher-order structure, often impairing function without breaking the peptide backbone.','Protein function depends on three-dimensional shape.','The monomers of proteins are:',['Nucleotides','Monosaccharides','Amino acids','Fatty acids'],2],
['Enzymes lower the energy barrier','Enzymes speed reactions by lowering activation energy. They are not consumed by the reaction and do not change its overall equilibrium. Binding can change an enzyme’s shape, as described by the induced-fit model.','An enzyme lowers activation energy, not the energy difference between reactants and products.','How do enzymes accelerate reactions?',['Raise activation energy','Lower activation energy','Become the final product','Always release ATP'],1],
['Nucleotides and energy','A nucleotide contains a sugar, phosphate group(s), and a nitrogenous base. Nucleotides build DNA and RNA. ATP is a nucleotide that transfers energy through coupled reactions; ATP itself is not a nucleic-acid polymer.','DNA and RNA are polymers; ATP is an individual nucleotide.','Which set describes a nucleotide?',['Glycerol and three fatty acids','Sugar, phosphate and base','Two amino acids','Glucose and fructose'],1]
]},
{id:'transport',title:'Across the cell membrane',subtitle:'Diffusion, osmosis & active transport',icon:'cells',color:'#e7f1ed',tone:'#648c79',source:'src13',ref:'3-1-the-cell-membrane',cards:[
['A selective boundary','The plasma membrane is a phospholipid bilayer with embedded proteins. Its hydrophobic interior allows small nonpolar molecules such as O₂ and CO₂ to cross readily. Ions usually require transport proteins.','A molecule’s size and polarity influence how it crosses.','Which crosses the lipid bilayer readily by simple diffusion?',['Na⁺','A large protein','O₂','Glucose'],2],
['Two kinds of diffusion','Simple diffusion moves substances directly through the membrane. Facilitated diffusion uses a channel or carrier. Both are passive: movement follows a concentration or electrochemical gradient without directly using ATP.','Using a protein does not automatically make transport active.','Glucose moving down its gradient through a carrier is:',['Primary active transport','Facilitated diffusion','Exocytosis','Phagocytosis'],1],
['Osmosis and cell volume','Osmosis is net water movement across a selectively permeable membrane. Water tends to move toward the side with more effective, nonpenetrating solute. A hypotonic solution can swell a cell; a hypertonic solution can shrink it.','Tonicity depends on solutes that cannot freely cross the membrane.','A red blood cell placed in a strongly hypotonic solution tends to:',['Shrink','Swell','Make ATP','Remain unchanged in all cases'],1],
['The sodium–potassium pump','The Na⁺/K⁺-ATPase uses ATP to move three Na⁺ out of the cell and two K⁺ into it per cycle. It maintains ion gradients used in excitability and secondary transport.','3 Na⁺ out, 2 K⁺ in, using ATP.','Per cycle, the sodium–potassium pump moves:',['2 Na⁺ out and 3 K⁺ in','3 Na⁺ in and 2 K⁺ out','3 Na⁺ out and 2 K⁺ in','Equal numbers in both directions'],2],
['Using an existing gradient','Secondary active transport couples movement down one solute’s electrochemical gradient to uphill movement of another. Sodium–glucose cotransport uses the sodium gradient maintained by the Na⁺/K⁺ pump. Symport moves coupled solutes in the same direction.','Secondary transport depends indirectly on energy used to establish a gradient.','Sodium and glucose moving together in the same direction is:',['Antiport','Symport','Simple diffusion','Exocytosis'],1],
['Moving larger cargo','Endocytosis brings material into a cell in vesicles. Phagocytosis engulfs large particles; receptor-mediated endocytosis selects specific cargo. Exocytosis releases vesicle contents when the vesicle fuses with the plasma membrane.','Endo = into the cell; exo = out of the cell.','A secretory vesicle releasing its contents uses:',['Osmosis','Exocytosis','Phagocytosis','Simple diffusion'],1]
]},
{id:'cells',title:'Inside the living cell',subtitle:'Organelles, division & the cell cycle',icon:'cells',color:'#eaeaf6',tone:'#7a79aa',source:'src29',ref:'3-2-the-cytoplasm-and-cellular-organelles',cards:[
['The nucleus and ribosomes','The nucleus houses most cellular DNA. The nucleolus is involved in ribosomal RNA production and ribosomal-subunit assembly. Ribosomes translate messenger RNA into polypeptides, whether free in the cytosol or associated with rough ER.','Ribosomes synthesize proteins; they do not copy DNA.','Where is messenger RNA translated into protein?',['Lysosomes','Ribosomes','Golgi cisternae','Centrioles'],1],
['The protein shipping route','Many secreted proteins are synthesized on ribosomes associated with rough endoplasmic reticulum, enter the ER, and travel in vesicles to the Golgi apparatus for modification and sorting. Vesicles then carry them to their destinations.','Rough ER → transport vesicle → Golgi → destination.','Which organelle modifies and sorts proteins from the ER?',['Golgi apparatus','Nucleolus','Centrosome','Peroxisome'],0],
['Energy and recycling','Mitochondria produce much of a cell’s ATP through aerobic metabolism. Lysosomes contain acidic digestive enzymes that break down engulfed material and worn-out cellular components.','Mitochondria support ATP production; lysosomes digest and recycle.','Which organelle contains acidic digestive enzymes?',['Nucleus','Lysosome','Ribosome','Golgi apparatus'],1],
['Preparing for division','The cell cycle includes G₁, S, G₂ and M phases. DNA is replicated in S phase. Mitosis separates duplicated chromosomes into two nuclei, while cytokinesis divides the cytoplasm.','DNA replication occurs before mitosis, during S phase.','During which phase is DNA replicated?',['G₁','S','G₂','M'],1],
['Mitosis in sequence','In prophase, chromosomes condense. At metaphase they align at the metaphase plate. In anaphase sister chromatids separate. In telophase new nuclear envelopes form around the separated chromosome sets.','Metaphase aligns; anaphase separates.','When do sister chromatids separate?',['Prophase','Metaphase','Anaphase','Telophase'],2]
]},
{id:'tissues',title:'Tissues: form meets function',subtitle:'Epithelium, connective tissue & histology',icon:'layers',color:'#e8eff8',tone:'#6d8eae',source:'src24',ref:'4-2-epithelial-tissue',cards:[
['Four basic tissue families','Epithelial tissue covers surfaces, lines cavities and forms glands. Connective tissue supports, binds and transports. Muscle tissue produces force. Nervous tissue enables rapid communication through neurons and their supporting cells.','A tissue includes cells and their surrounding extracellular components.','Which basic tissue type includes blood?',['Epithelial','Connective','Muscle','Nervous'],1],
['Epithelial layers','Simple epithelium has one cell layer. Stratified epithelium has multiple layers, with only basal cells contacting the basement membrane. Pseudostratified epithelium is one layer: every cell contacts the basement membrane, but not every cell reaches the free surface.','Pseudostratified looks layered but is a single layer.','In pseudostratified epithelium, which statement is correct?',['No cells touch the basement membrane','All cells reach the free surface','All cells contact the basement membrane','There are always three cell layers'],2],
['Shape predicts function','Squamous cells are thin and flattened, cuboidal cells have similar height and width, and columnar cells are taller than wide. Stratified epithelia are named by the shape of their surface cells. Simple squamous epithelium permits efficient exchange.','Alveolar gas exchange relies on a thin diffusion barrier.','Which epithelium is best suited to rapid diffusion in alveoli?',['Stratified cuboidal','Simple squamous','Transitional','Stratified squamous'],1],
['Avascular does not mean unsupported','Epithelia contain no blood vessels. Nutrients diffuse from underlying connective tissue across the basement membrane. Many epithelia regenerate rapidly and have a distinct apical surface facing a lumen or the exterior.','Epithelial nutrition comes from nearby vascular connective tissue.','How do epithelial cells generally receive nutrients?',['Blood vessels inside the epithelium','Diffusion from underlying tissue','Only through the apical air space','From keratin'],1],
['The extracellular matrix matters','Connective tissue has cells embedded in an extracellular matrix of ground substance and fibers. Tendons are rich in aligned collagen, adipose stores energy and cushions, and reticular tissue provides a supporting framework in organs such as lymph nodes.','The matrix helps determine a connective tissue’s mechanical properties.','Which tissue forms the main load-bearing component of most tendons?',['Dense regular connective tissue','Simple cuboidal epithelium','Hyaline cartilage','Nervous tissue'],0],
['Cartilage in context','Hyaline cartilage supports the trachea and covers articular surfaces in many joints. Elastic cartilage supports the external ear and epiglottis. Fibrocartilage resists compression and tension in structures such as intervertebral discs.','Elastic: flexibility. Fibrocartilage: resistance to compression and tension.','Which cartilage supports the external ear?',['Fibrocartilage','Elastic cartilage','Articular hyaline cartilage','Calcified bone'],1]
]},
{id:'skin',title:'Skin & protective membranes',subtitle:'Skin layers, glands & body coverings',icon:'layers',color:'#faeae5',tone:'#b17b65',source:'src38',ref:'5-1-layers-of-the-skin',cards:[
['Two layers of skin','Skin consists of an epidermis and a dermis. The epidermis is keratinized stratified squamous epithelium. The dermis is vascular connective tissue. The hypodermis lies beneath the skin and is not part of the skin proper.','Epidermis + dermis = skin proper.','Which layer is vascular connective tissue?',['Epidermis','Stratum corneum','Dermis','Stratum lucidum'],2],
['Layers of the epidermis','From deep to superficial: basale, spinosum, granulosum and corneum. Thick skin on palms and soles also has a stratum lucidum between granulosum and corneum. Cells become more keratinized as they approach the surface.','Lucidum is a feature of thick skin.','Which epidermal layer is deepest?',['Corneum','Granulosum','Basale','Lucidum'],2],
['Papillary and reticular dermis','The superficial papillary layer is mainly areolar connective tissue. The deeper reticular layer is mainly dense irregular connective tissue. Dermal vessels, nerves and glands support sensation, thermoregulation and other skin functions.','Papillary = superficial; reticular = deeper.','Which tissue predominates in the reticular dermis?',['Dense irregular connective tissue','Stratified squamous epithelium','Hyaline cartilage','Cardiac muscle'],0],
['Mucous and serous membranes','Mucous membranes line passages that open to the exterior, such as the digestive tract. Serous membranes line closed ventral body cavities and cover organs. Their parietal layer lines the cavity and their visceral layer covers the organ.','Parietal = wall; visceral = organ.','The layer of a serous membrane directly covering an organ is:',['Parietal','Visceral','Cutaneous','Synovial cartilage'],1],
['Repair and scarring','Regeneration replaces damaged tissue with the same tissue type. Fibrosis forms scar tissue, which restores structural continuity but may not restore the original function. Apoptosis is regulated cell death; necrosis is injury-associated cell death.','Repair can combine regeneration with fibrosis.','Replacement of damaged tissue by scar tissue is called:',['Osmosis','Fibrosis','Mitosis alone','Transduction'],1]
]},
{id:'skeleton',title:'The skeletal framework',subtitle:'Bone structure, shapes & landmarks',icon:'bone',color:'#f4eee1',tone:'#a18b5e',source:'src21',ref:'6-3-bone-structure',cards:[
['Axial and appendicular','The adult skeleton typically contains 206 bones, with normal variation. The axial skeleton includes the skull, vertebral column and thoracic cage. The appendicular skeleton includes the limbs and the pectoral and pelvic girdles.','Girdles belong to the appendicular skeleton.','Which belongs to the appendicular skeleton?',['Sternum','Sacrum','Scapula','Hyoid'],2],
['Bone shapes','Long bones are longer than they are wide, such as the femur. Short bones are roughly cube-shaped, such as carpals. Flat bones include the sternum. Vertebrae are irregular bones. Sesamoid bones, such as the patella, develop within tendons.','Short bones are roughly cuboidal, not spherical.','The patella is classified as which shape?',['Flat','Sesamoid','Long','Irregular vertebral'],1],
['Inside a long bone','The diaphysis is the shaft and the epiphyses are the ends. Compact bone forms a dense outer region; spongy bone contains trabeculae. Articular cartilage covers joint surfaces, while periosteum covers most external bone surfaces elsewhere.','The shaft is the diaphysis.','What is the shaft of a long bone called?',['Epiphysis','Diaphysis','Periosteum','Epiphyseal plate'],1],
['Bone cells','Osteoblasts produce bone matrix. Osteocytes are mature bone cells housed in lacunae and connected through canaliculi. Osteoclasts resorb bone. Bone is living tissue that is continuously remodeled.','Blasts build; clasts resorb; cytes maintain and sense load.','Which cell resorbs bone?',['Osteoblast','Osteocyte','Osteoclast','Chondrocyte'],2],
['Reading bone landmarks','A foramen is an opening through bone. A fossa is a depression. A condyle is a rounded articular surface. A tuberosity is a roughened projection, often serving as an attachment site. Names describe useful structural clues.','Foramen = opening; fossa = depression.','The foramen magnum is best described as:',['A tendon attachment ridge','A large opening','A rounded joint surface','A small pit'],1]
]},
{id:'axial',title:'Skull, spine & thoracic cage',subtitle:'Explore the body’s central support',icon:'bone',color:'#efece4',tone:'#a19673',source:'src33',ref:'7-3-the-vertebral-column',cards:[
['Cranial and facial bones','The skull’s cranial bones enclose the brain. Facial bones form the framework of the face. The mandible is the lower jaw, while the paired maxillae form the upper jaw. Sutures unite most skull bones by fibrous joints.','Mandible = lower jaw; maxillae = upper jaw.','Which bone forms the lower jaw?',['Maxilla','Mandible','Sphenoid','Ethmoid'],1],
['Vertebral regions','The vertebral column typically has seven cervical, twelve thoracic and five lumbar vertebrae, followed by the sacrum and coccyx. Thoracic vertebrae articulate with ribs. The atlas is C1 and the axis is C2.','7 cervical, 12 thoracic, 5 lumbar.','Which region has twelve vertebrae?',['Cervical','Thoracic','Lumbar','Sacral in the adult'],1],
['Atlas and axis','The atlas supports the skull. Its articulation with the occipital condyles permits much of the nodding motion. The dens of the axis acts as a pivot for rotation of the atlas and head.','C1 supports; the dens of C2 provides a pivot.','The dens is a feature of:',['Atlas (C1)','Axis (C2)','Sacrum','Sternum'],1],
['The thoracic cage','The sternum, ribs and thoracic vertebrae protect thoracic organs. Ribs 1–7 attach to the sternum by their own costal cartilages. Ribs 8–10 attach indirectly. Ribs 11–12 have no anterior attachment to the sternum.','Floating ribs are ribs 11 and 12.','Which ribs are normally called floating ribs?',['1–2','6–7','8–10','11–12'],3],
['Intervertebral discs','Most adjacent vertebral bodies are separated by discs. Each disc has an outer annulus fibrosus and an inner nucleus pulposus. The discs help distribute loads and permit movement between vertebrae.','Annulus outside; nucleus inside.','What is the inner region of an intervertebral disc?',['Annulus fibrosus','Nucleus pulposus','Spinous process','Lamina'],1]
]},
{id:'muscles',title:'Muscles in motion',subtitle:'Muscle tissue, actions & contraction',icon:'muscle',color:'#f8e7e8',tone:'#b9797f',source:'src45',ref:'10-2-skeletal-muscle',cards:[
['Three types of muscle','Skeletal muscle fibers are striated and usually have many peripheral nuclei. Cardiac muscle is striated, branched and joined by intercalated discs. Smooth muscle lacks striations and occurs in many hollow-organ walls.','Both skeletal and cardiac muscle are striated.','Which muscle has intercalated discs?',['Skeletal','Cardiac','Smooth','All three equally'],1],
['A hierarchy of connective tissue','Endomysium surrounds an individual skeletal muscle fiber. Perimysium surrounds a fascicle, or bundle of fibers. Epimysium surrounds the whole muscle. These coverings help transmit force.','Endo: fiber. Peri: fascicle. Epi: whole muscle.','Which covering surrounds a fascicle?',['Endomysium','Perimysium','Epimysium','Periosteum'],1],
['Joint actions','Flexion generally decreases the angle at a joint; extension increases it. Abduction moves away from the body’s midline; adduction moves toward it. Movement terminology is described relative to anatomical position.','Abduction = away; adduction = toward.','Moving the arm laterally away from the trunk is:',['Adduction','Abduction','Pronation','Depression'],1],
['Pronation and supination','These forearm movements occur at the radioulnar joints. In supination, the radius and ulna lie parallel and the palm faces anteriorly in anatomical position. During pronation, the radius crosses over the ulna.','These are forearm movements, not movements of the lower-leg bones.','During forearm pronation, which bone crosses over the other?',['Ulna crosses radius','Radius crosses ulna','Tibia crosses fibula','Humerus crosses radius'],1],
['Sliding filaments','A sarcomere extends from one Z disc to the next. During contraction, thin and thick filaments slide past one another; the filaments themselves do not shorten. Calcium binds troponin, shifting tropomyosin so myosin can bind actin.','Sarcomeres shorten; actin and myosin filaments retain their lengths.','Which protein binds calcium to initiate skeletal-muscle contraction?',['Tropomyosin','Troponin','Collagen','Keratin'],1],
['Motor units and force','A motor unit is one motor neuron and every skeletal muscle fiber it innervates. Recruiting more motor units can increase force. Isometric contraction develops tension without a change in overall muscle length; eccentric contraction develops tension while lengthening.','Contraction means active tension, not always shortening.','A muscle actively producing tension while lengthening is undergoing:',['Concentric contraction','Eccentric contraction','Complete relaxation','No contraction'],1]
]},
{id:'neuro',title:'Neurons & their support team',subtitle:'Nervous tissue, myelin & signaling',icon:'brain',color:'#eee7f6',tone:'#9675ae',source:'src23',ref:'12-2-nervous-tissue',cards:[
['The parts of a neuron','The soma contains the nucleus and much of the cell’s biosynthetic machinery. Dendrites commonly receive input. The axon carries signals toward its terminals, which communicate with other cells at synapses.','Dendrites receive; axons carry output in the usual signaling pattern.','Which part of a neuron contains its nucleus?',['Axon terminal','Soma','Myelin sheath','Synaptic cleft'],1],
['Myelin in the CNS and PNS','Myelin is a multilayered membrane sheath around many axons. Oligodendrocytes make CNS myelin and can myelinate segments of multiple axons. A myelinating Schwann cell forms one internode on one PNS axon.','Oligodendrocyte: CNS. Schwann cell: PNS.','Which cell forms myelin in the peripheral nervous system?',['Astrocyte','Microglial cell','Schwann cell','Ependymal cell'],2],
['Nodes of Ranvier','Nodes are gaps between myelin segments. Action potentials are regenerated at nodes, allowing rapid saltatory conduction. Myelin reduces current leakage and helps electrical signals travel efficiently between nodes.','Saltatory conduction regenerates the action potential at nodes.','The gaps between myelin segments are called:',['Synaptic clefts','Nodes of Ranvier','Dendritic spines','Nucleoli'],1],
['Glia do different jobs','Astrocytes support the CNS environment and help maintain the blood–brain barrier. Microglia provide immune surveillance and phagocytosis. Ependymal cells line ventricles and the central canal; specialized choroid plexus epithelium produces most CSF.','Not every ependymal cell is a CSF-producing choroid plexus cell.','Which CNS glial cells specialize in immune surveillance and phagocytosis?',['Microglia','Oligodendrocytes','Satellite cells','Schwann cells'],0],
['Gray matter and white matter','Gray matter contains neuronal cell bodies, dendrites, synapses and axons. White matter is rich in myelinated axons. Gray matter is not simply “unmyelinated,” and white matter is not composed of myelin alone.','The distinction reflects tissue composition, not an absolute presence or absence of myelin.','White matter is especially rich in:',['Keratin','Myelinated axons','Articular cartilage','Red blood cells'],1]
]},
{id:'brain',title:'A tour of the brain',subtitle:'Cerebrum, cerebellum & brainstem',icon:'brain',color:'#f3e6ef',tone:'#a26b96',source:'src28',ref:'13-2-the-central-nervous-system',cards:[
['Lobes of the cerebrum','The frontal lobe contributes to voluntary motor control, planning and behavior. The parietal lobe integrates somatic sensation. The temporal lobe contributes to hearing and memory. The occipital lobe is central to visual processing.','Brain functions are distributed, even when a region has a prominent role.','Which lobe contains the primary visual cortex?',['Frontal','Parietal','Temporal','Occipital'],3],
['The central sulcus','The central sulcus separates the frontal and parietal lobes. The precentral gyrus contains primary motor cortex; the postcentral gyrus contains primary somatosensory cortex.','Precentral: motor. Postcentral: somatosensory.','Primary somatosensory cortex is located in the:',['Precentral gyrus','Postcentral gyrus','Medulla','Cerebellar vermis'],1],
['Thalamus and hypothalamus','The thalamus relays much sensory information to the cerebral cortex. The hypothalamus helps regulate homeostasis through autonomic and endocrine pathways, including temperature, hunger, thirst and pituitary control.','Hypothalamus: homeostatic regulation.','Which structure helps regulate hunger, thirst and body temperature?',['Hypothalamus','Occipital cortex','Corpus callosum','Cerebellar hemisphere'],0],
['Cerebellum and brainstem','The cerebellum helps coordinate movement, balance and motor learning. The brainstem consists of the midbrain, pons and medulla oblongata. It contains major pathways and nuclei important for basic functions and cranial nerves.','The brainstem includes midbrain, pons and medulla.','Which is a component of the brainstem?',['Caudate nucleus','Pons','Parietal lobe','Corpus callosum'],1],
['Cerebrospinal fluid','CSF is produced mainly by the choroid plexuses. It circulates through the ventricles and into the subarachnoid space, supporting and cushioning the CNS. The lateral ventricles connect with the third ventricle through the interventricular foramina.','CSF normally occupies the subarachnoid space.','Where does CSF surround the brain and spinal cord?',['Epidural fat only','Subarachnoid space','Within compact bone','Inside arteries'],1]
]},
{id:'spinal',title:'Spinal cord & meninges',subtitle:'Protective layers, roots & pathways',icon:'spine',color:'#e6eff3',tone:'#6892a4',source:'src27',ref:'13-2-the-central-nervous-system',cards:[
['Where the spinal cord ends','The adult spinal cord usually ends near the L1–L2 vertebral level as the conus medullaris. Nerve roots continue below it as the cauda equina. The cord does not divide into those roots at its tip.','Conus medullaris = tapered cord; cauda equina = descending nerve roots.','The tapered end of the spinal cord is the:',['Cauda equina','Conus medullaris','Dorsal root ganglion','Filum terminale'],1],
['Three meningeal layers','From superficial to deep, the meninges are dura mater, arachnoid mater and pia mater. Pia closely follows the surface of the spinal cord. Arachnoid bridges over the CSF-containing subarachnoid space.','Dura → arachnoid → pia.','Which meningeal layer adheres closely to the cord surface?',['Dura mater','Arachnoid mater','Pia mater','Epidural space'],2],
['Spaces around the cord','The spinal epidural space lies outside the dura and contains fat and vessels. The subarachnoid space lies between arachnoid and pia and contains CSF. These spaces are anatomically distinct.','Epidural: outside dura. Subarachnoid: between arachnoid and pia.','Which spinal space contains fat and a venous plexus?',['Central canal','Epidural space','Subarachnoid space','Ventricular space'],1],
['Dorsal in, ventral out','Dorsal roots carry sensory axons toward the spinal cord. Dorsal root ganglia contain sensory neuron cell bodies. Ventral roots carry motor axons away. Once joined, a spinal nerve contains both sensory and motor fibers.','Roots differ in function; spinal nerves are mixed.','Sensory neuron cell bodies are found in the:',['Ventral root','Dorsal root ganglion','Anterior median fissure','Pia mater'],1],
['Gray matter in the cord','Spinal gray matter has a butterfly-like shape in cross-section. Dorsal horns receive sensory input. Ventral horns contain somatic motor neuron cell bodies. White-matter tracts surrounding the gray matter carry ascending and descending information.','Dorsal horn: sensory processing. Ventral horn: somatic motor output.','Somatic motor neuron cell bodies lie in the:',['Ventral horn','Dorsal root ganglion','Posterior column only','Arachnoid mater'],0]
]},
{id:'senses',title:'Sensing the world',subtitle:'Peripheral nerves, receptors & reflexes',icon:'eye',color:'#e6f1ed',tone:'#6d9887',source:'src26',ref:'14-1-sensory-perception',cards:[
['Peripheral pathways','The peripheral nervous system links the CNS to the body through nerves and ganglia. Sensory (afferent) pathways carry information toward the CNS, and motor (efferent) pathways carry commands toward effectors.','Afferent arrives; efferent exits.','Afferent pathways carry information:',['Toward the CNS','Only to muscles','Away from the CNS','Only between cerebral hemispheres'],0],
['Receptors by location','Exteroceptors monitor stimuli from the external environment. Interoceptors monitor internal conditions. Proprioceptors provide information about body position and movement from structures such as muscles, tendons and joints.','Proprioception lets you sense limb position without looking.','Which receptor category provides information about joint position?',['Photoreceptor only','Proprioceptor','Olfactory receptor','Taste receptor'],1],
['Receptors by stimulus','Mechanoreceptors respond to physical deformation, such as pressure or stretch. Thermoreceptors respond to temperature. Chemoreceptors respond to chemicals. Nociceptors respond to potentially damaging stimuli. Transduction converts stimulus energy into an electrical response.','Stimulus type and receptor location are two different classification systems.','A receptor responding to stretch is a:',['Photoreceptor','Mechanoreceptor','Chemoreceptor','Olfactory receptor'],1],
['Discrimination and adaptation','Small receptive fields and dense innervation improve spatial discrimination, as in fingertips. Rapidly adapting receptors emphasize changes in a stimulus; slowly adapting receptors continue responding during sustained stimulation.','Adaptation changes receptor response; it does not mean the stimulus disappeared.','Why can fingertips distinguish two nearby points better than the upper arm?',['Larger receptive fields','Smaller receptive fields and denser innervation','No sensory nerves','Only motor neurons'],1],
['A reflex arc','A basic reflex pathway includes a receptor, sensory neuron, integration center, motor neuron and effector. Some reflex pathways contain interneurons. A monosynaptic stretch reflex directly links a sensory neuron to a motor neuron.','Not all reflexes require conscious cortical processing.','Which component carries a reflex command to a skeletal muscle?',['Sensory receptor','Motor neuron','Dorsal root ganglion soma','Photoreceptor'],1],
['Cranial nerves in order','I olfactory, II optic, III oculomotor, IV trochlear, V trigeminal, VI abducens, VII facial, VIII vestibulocochlear, IX glossopharyngeal, X vagus, XI accessory and XII hypoglossal. Their functions can be sensory, motor or both.','VIII carries hearing and equilibrium information.','Which cranial nerve carries hearing and equilibrium information?',['V trigeminal','VII facial','VIII vestibulocochlear','XII hypoglossal'],2]
]},
{id:'pharmacology',title:'Acetylcholine & its receptors',subtitle:'Autonomic signaling & receptor types',icon:'flask',color:'#eee9f5',tone:'#8c78aa',source:'src2',ref:'15-1-divisions-of-the-autonomic-nervous-system',cards:[
['One transmitter, different receptors','Acetylcholine acts on nicotinic and muscarinic receptors. Nicotinic receptors are ligand-gated ion channels. Muscarinic receptors are G-protein-coupled receptors. The response depends on receptor subtype and tissue.','The same neurotransmitter can cause different effects at different receptors.','Nicotinic acetylcholine receptors are:',['Ligand-gated ion channels','Steroid hormones','Transport vesicles','DNA polymerases'],0],
['Autonomic ganglia','Both sympathetic and parasympathetic preganglionic neurons release acetylcholine onto nicotinic receptors in autonomic ganglia. Parasympathetic postganglionic neurons generally release acetylcholine onto muscarinic receptors at target organs.','Both autonomic divisions use acetylcholine at their ganglia.','Which transmitter is released by both sympathetic and parasympathetic preganglionic neurons?',['Dopamine','Acetylcholine','Serotonin','Histamine'],1],
['A sympathetic exception','Most sympathetic postganglionic neurons release norepinephrine. A prominent exception is the sympathetic supply to eccrine sweat glands, which releases acetylcholine acting on muscarinic receptors.','Sweat glands are sympathetic but cholinergic.','Sympathetic fibers to eccrine sweat glands typically release:',['Acetylcholine','Only epinephrine','Glutamate','GABA'],0],
['Blocking cholinergic signaling','An antagonist binds a receptor and reduces activation by an agonist. Antimuscarinic drugs block muscarinic acetylcholine receptors. They are distinct from blockers of nicotinic receptors at the neuromuscular junction.','“Anticholinergic” is often used for antimuscarinic drugs, but receptor specificity matters.','An antimuscarinic drug directly targets:',['Muscarinic receptors','All ion channels','Actin filaments','Hemoglobin'],0],
['The somatic neuromuscular junction','Somatic motor neurons release acetylcholine onto nicotinic receptors at skeletal-muscle motor end plates. Acetylcholinesterase breaks down acetylcholine in the synaptic cleft, helping terminate the signal.','Skeletal-muscle motor end plates use nicotinic, not muscarinic, receptors.','Which enzyme breaks down acetylcholine?',['Acetylcholinesterase','DNA ligase','Amylase','Pepsin'],0]
]}
];
const CORRECTIONS=[
['Forearm rotation','The axial-muscle key describes supination/pronation using “lower limb bones.” The lessons correctly use radius and ulna in the forearm.','9-5-types-of-body-movements'],
['Epithelial layers','Only basal cells touch the basement membrane in stratified epithelium. In pseudostratified epithelium, all cells touch the basement membrane, but not all reach the free surface.','4-2-epithelial-tissue'],
['Spinal cord termination','The adult conus usually lies near L1–L2. The cauda equina consists of descending nerve roots; it is not the cord splitting into fibers at its end.','13-2-the-central-nervous-system'],
['Bone shapes','Short bones are roughly cuboidal. Sesamoid bones develop in tendons; “inside a muscle” is not the defining criterion.','6-2-bone-classification'],
['Active transport','A polar or large solute does not necessarily require active transport. Facilitated diffusion can move polar solutes down a gradient without ATP.','3-1-the-cell-membrane'],
['Gray matter and CSF','Gray matter is not simply “unmyelinated.” Both the central canal and subarachnoid space can contain CSF, so the original single-answer question is ambiguous. The revised questions specify the intended location.','13-2-the-central-nervous-system'],
['Muscle contraction','Active contraction can shorten, maintain length, or lengthen a muscle. A fixed 50% shortening rule is not used in the lessons.','10-4-nervous-system-control-of-muscle-tension'],
];
// Correct source identities after archive import.
const SOURCE_FIX={foundations:'src44',cells:'src32',skin:'src39',axial:'src35',muscles:'src47',brain:'src30',spinal:'src29',senses:'src28'};
UNITS.forEach(u=>{if(SOURCE_FIX[u.id])u.source=SOURCE_FIX[u.id]});
UNITS.push({id:'special-senses',title:'Hearing, balance & chemical senses',subtitle:'Follow sound and sensory transduction',icon:'eye',color:'#e7eef8',tone:'#718baa',source:'src11',ref:'14-1-sensory-perception',cards:[
['From air to the inner ear','Sound travels through the external auditory canal to the tympanic membrane. The malleus, incus and stapes transmit vibrations through the middle ear. The stapes footplate acts at the oval window, transferring vibrations into inner-ear fluid.','Tympanic membrane → malleus → incus → stapes → oval window.','Which ossicle contacts the oval window?',['Malleus','Incus','Stapes','Hyoid'],2],
['Hearing in the cochlea','The cochlea contains the organ of Corti, including sensory hair cells. Movement of the basilar membrane bends hair-cell stereocilia and changes transmitter release. Cochlear nerve fibers carry auditory information toward the brainstem.','Hair cells transduce mechanical movement into an electrical response.','Which structure contains the organ of Corti?',['Cochlea','Tympanic membrane','External auditory canal','Semicircular canal ampulla'],0],
['Two kinds of equilibrium information','The semicircular ducts detect angular acceleration through sensory structures in their ampullae. The utricle and saccule detect linear acceleration and head orientation relative to gravity through their maculae.','Semicircular ducts: angular acceleration. Utricle and saccule: linear acceleration and gravity.','Which structures detect linear acceleration and head tilt?',['Auditory ossicles','Utricle and saccule','External ear','Cochlear duct only'],1],
['Taste and smell','Gustation and olfaction are chemical senses. Taste receptor cells occur in taste buds, while olfactory receptor neurons occur in olfactory epithelium. Flavor combines taste, smell and other sensory input.','Taste and smell contribute together to flavor.','Taste and smell are classified as:',['Mechanical senses','Chemical senses','Proprioceptive senses','Thermal senses'],1]
]});
UNITS.push({id:'kinases',title:'Cell signals & kinase inhibitors',subtitle:'Molecular targets & receptor signaling',icon:'flask',color:'#eee8f5',tone:'#8f78aa',source:'src49',url:'https://www.cancer.gov/publications/dictionaries/cancer-terms/def/tyrosine-kinase-inhibitor',cards:[
['Tyrosine kinases are signaling enzymes','Tyrosine kinases participate in cell signaling, growth and division. A tyrosine kinase inhibitor reduces the activity of a targeted kinase. Some cancers have overactive kinase signaling, creating a target for therapy.','A kinase inhibitor targets an enzyme involved in signaling.','Tyrosine kinase inhibitors are designed to reduce the activity of:',['Tyrosine kinases','All neurotransmitters','Every cell membrane','Hemoglobin'],0],
['Targeted does not mean universal','A targeted therapy acts on a particular molecular feature. Different cancers can have different signaling abnormalities, so an inhibitor’s relevance depends on the target present.','The molecular target matters.','Why is one kinase inhibitor not appropriate for every cancer?',['All cancers have identical signaling','Cancers can have different molecular targets','Kinases occur only in bacteria','Targeted therapies never interact with cells'],1],
['Separate growth signals from the enzyme site','A receptor’s extracellular ligand-binding region and its intracellular kinase region are distinct. ATP binds to the intracellular kinase domain; growth factors bind to the extracellular domain.','A receptor can have different regions for ligand binding and intracellular signaling.','A growth-factor binding region and an intracellular kinase region are:',['Always the same site','Distinct functional regions','Two types of membrane lipid','Absent from all receptor proteins'],1]
]});
UNITS.push({id:'scaleup',title:'From laboratory to manufacturing',subtitle:'Process chemistry & manufacturing',icon:'flask',color:'#f1eee5',tone:'#9b8865',source:'src50',url:'https://doi.org/10.1021/op9800865',cards:[
['A route must work at its intended scale','A useful large-scale route must account for process safety, impurity control, availability of materials and work-up, as well as the desired chemical transformation.','Chemical yield is only one part of process suitability.','Which factor matters when selecting a manufacturing route?',['Only the product name','Safety and impurity control as well as yield','Only the color of the product','Ignoring work-up'],1],
['Intermediate stability shapes the route','The presentation describes an intermediate that was thermally and hydrolytically unstable. Such stability constraints can make isolation or an aqueous work-up unsuitable and motivate changes to the reaction sequence.','A workable transformation can still have an impractical intermediate.','Why can an unstable intermediate complicate scale-up?',['It can limit isolation and work-up options','It guarantees improved purity','It removes the need for evaluation','It prevents all chemical reactions'],0],
['Look beyond the final reaction','The analysis discusses filtration, byproducts and solvent choice as part of route development. A complete process includes the steps needed to separate, purify and handle the product, not only the bond-forming reaction.','Work-up and purification are part of the process.','Which is part of a complete manufacturing process?',['Only drawing the final structure','Separation and purification','Ignoring byproducts','Reporting yield without context'],1]
]});
const FIGURES={
foundations:[[44,10,'Anatomical directions'],[44,10,'Directional relationships'],[44,10,'Proximal and distal'],[44,5,'Anatomical planes'],[44,2,'Temperature regulation and negative feedback']],
chemistry:[[15,13,'Molecular examples'],[15,6,'Dehydration synthesis and hydrolysis'],[15,18,'The peptide bond'],[15,2,'Induced fit model'],[15,3,'Parts of a nucleotide']],
transport:[[15,17,'A phospholipid'],[13,3,'Carrier-mediated and channel-mediated diffusion'],[13,6,'Tonicity and red blood cells'],[13,1,'The sodium–potassium pump'],[13,0,'Primary and secondary active transport'],[13,10,'Endocytosis and exocytosis']],
cells:[[32,6,'Transcription and translation'],[32,6,'Protein synthesis overview'],[24,18,'Cellular recycling and cell death: related processes'],[32,5,'The cell cycle'],[32,4,'Stages of mitosis']],
tissues:[[24,12,'The four basic tissue families'],[24,22,'Pseudostratified epithelium'],[24,3,'Simple squamous epithelium'],[24,13,'Epithelium and underlying tissue'],[24,17,'Connective tissue matrix'],[24,6,'Cartilage locations']],
skin:[[39,6,'Skin layers'],[39,19,'Layers of thick and thin skin'],[39,13,'Skin cross-section'],[44,9,'Parietal and visceral pleura'],[24,8,'Tissue repair']],
skeleton:[[21,15,'Axial and appendicular skeleton'],[21,13,'Bone shape classification'],[21,12,'Long bone anatomy'],[24,1,'Bone cell types'],[21,5,'Foramen magnum']],
axial:[[35,21,'Anterior skull'],[35,1,'The axial skeleton'],[35,20,'Axis and dens'],[35,22,'The thoracic cage'],[35,15,'Lumbar vertebra: a related structural view']],
muscles:[[24,16,'Cardiac muscle and intercalated discs'],[47,22,'Muscle connective-tissue coverings'],[47,15,'Shoulder abduction'],[47,13,'Forearm pronation'],[39,5,'Striated skeletal muscle'],[40,15,'Motor unit recruitment']],
neuro:[[23,3,'Neuron structure'],[23,7,'Schwann cells and satellite cells'],[23,5,'Nodes between myelin segments'],[23,9,'CNS glial cell types'],[30,7,'Gray and white matter']],
brain:[[30,5,'Cerebral regions'],[30,1,'Central sulcus and adjacent gyri'],[30,4,'Midsagittal brain'],[30,2,'Major brain divisions'],[30,8,'The ventricular system']],
spinal:[[29,2,'Cord, conus and cauda equina'],[29,3,'Spinal cord and meninges'],[29,3,'Spaces around the spinal cord'],[29,3,'Spinal roots and ganglia'],[29,3,'Spinal cord cross-section']],
senses:[[28,3,'Peripheral nervous system'],[12,7,'Sensory receptors in skin'],[12,10,'Receptor types'],[12,8,'Receptive fields and discrimination'],[12,0,'A sensory pathway'],[28,2,'The cranial nerves']],
'special-senses':[[21,4,'Regions of the ear'],[21,4,'Inner ear and cochlea'],[21,4,'Vestibular structures'],[11,0,'Special senses worksheet']],
pharmacology:[[48,4,'Cholinergic receptor overview'],[48,4,'Cholinergic receptor overview'],[48,4,'Cholinergic receptor overview'],[48,5,'Muscarinic antagonists'],[48,2,'Acetylcholine signaling']],
kinases:[[49,0,'Receptor signaling overview']],scaleup:[[50,1,'Project background'],[50,6,'Intermediate stability'],[50,8,'Process development']]
};
FIGURES.pharmacology=[[2,18,'Nicotinic receptors and ion flow'],[2,7,'Parasympathetic preganglionic and postganglionic signaling'],[2,9,'Sympathetic preganglionic signaling: compare with the exception in the lesson'],[2,14,'Blocking a muscarinic receptor'],[2,5,'Acetylcholine at a synapse']];
